# Birds CUB dataset
birds_images_path: '/nethome/hshah310/Text-to-Image-Synthesis/BirdsDataset/CUB_200_2011/CUB_200_2011/images/'
birds_embedding_path: '/nethome/hshah310/Text-to-Image-Synthesis/BirdsDataset/cub_icml/'
birds_text_path: '/nethome/hshah310/Text-to-Image-Synthesis/BirdsDataset/cvpr2016_cub/text_c10/'
birds_dataset_path: '/nethome/hshah310/Text-to-Image-Synthesis/BirdsDataset/birds.hdf5'
val_split_path: '/nethome/hshah310/Text-to-Image-Synthesis/BirdsDataset/cub_icml/valclasses.txt'
train_split_path: '/nethome/hshah310/Text-to-Image-Synthesis/BirdsDataset/cub_icml/trainclasses.txt'
test_split_path: '/nethome/hshah310/Text-to-Image-Synthesis/BirdsDataset/cub_icml/testclasses.txt'


# flowers dataset (TODO update paths)
flowers_images_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/'
flowers_embedding_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/'
flowers_text_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/cvpr2016_flowers/text_c10/'
flowers_dataset_path: '/content/drive/My Drive/GaTech/Summer20/RL-NLP Research/Text-to-Image-Synthesis/flowers.hdf5'

flowers_val_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/valclasses.txt'
flowers_train_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/trainclasses.txt'
flowers_test_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/testclasses.txt'